# -*- coding: utf-8 -*-
"""Transcription_by_whisper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9Sw4AZSJNp4SHW1071M4oNFNmkimAuj
"""

#起動前に音声をアップロードすること

!pip install git+https://github.com/openai/whisper.git

import whisper

# Load the Whisper model
model = whisper.load_model("medium") # You can choose other models like "small", "medium", "large"

# Transcribe the audio file
result = model.transcribe(R"audeo.mp3") # Replace "audio.mp3" with your audio file

# Print the transcribed text
print(result["text"])